const kaynaklar = {
      "Süryani Kaynakları": [
        { yazar: "Gregory Abû’l Farac (Bar Hebraeus)", eser: "Tarihu'z-zaman", aciklama: "1225’te Malatya’da doğan Abu’l Farac (Bar Hebraeus), asıl adı Aaron olan, Yahudi kökenli bir düşünürdür. Hristiyanlığı benimseyerek Monofizit inanca yönelmiş ve Süryani kimliğini benimsemiştir. Felsefe, tarih, tıp, ilahiyat ve dil gibi pek çok alanda Süryanice ve Arapça kaleme aldığı eserlerle öne çıkmıştır. 1246’da piskopos olan Bar Hebraeus, Süryani Katolikosu olarak görev yapmış, seyahatleri sırasında farklı kültür ve inançlarla tanışmıştır. Bu birikimini eserlerine yansıtan Bar Hebraeus, 1286’da Meraga’da vefat etmiş ve Musul’da defnedilmiştir. Claude Cahen, onu Bizans sonrası ve Osmanlı öncesi Anadolu’da yaşamış en önemli Yahudi şahsiyetlerden biri olarak tanımlar. Süryani dili üzerine yaptığı çalışmalar, bu dilin korunmasına ve yaşatılmasına önemli katkılar sağlamıştır." },
        { yazar: "Süryani Mihail", eser: "Vekayinâme", aciklama: "Süryani Mihail, 1126 yılında Malatya'nın Melitene bölgesinde doğmuş, eğitimini bir manastırda almıştır. 1166’da Süryani Ortodoks Kilisesi’nin patriği olarak göreve gelmiş ve ölümüne dek bu görevi sürdürmüştür. Patrikliği süresince Kudüs ve Antakya’daki Haçlılarla ilişki kurmuş, Bizans İmparatoru’yla ise inanç meselelerine dair yazışmalar yapmıştır. Tarihi Yaratılış’tan kendi dönemine kadar ele alan eseri, hem kapsamlı hem de değerlidir. Ayinler, kilise hukuku ve doktrine dair pek çok yazı kaleme almış, vaazlarıyla ruhani etkisini artırmıştır. 1182’de Sultan II. Kılıç Arslan ile görüşmesi, onun diplomatik yönünü de ortaya koyar. 1199 yılında 72 yaşında hayatını kaybeden Mihail, Bar Sauma Manastırı’na defnedilmiştir." },
        { yazar: "Anonim Süryani Vekayinâmesi", eser: "I. ve II. Haçlı Seferleri Vekayinamesi", aciklama: "Süryani bakış açısıyla I. ve II. Haçlı Seferleri’ni anlatır." }
      ],
      "İslâm Kaynakları": [
        { yazar: "Siret-i İbn-i Hişâm", eser: "İslam Tarihi", aciklama: "Basralı’dır. Eseri asıl olarak, İbn-i îshâk adlı bir alim yazmıştır fakat düzenlemesini İbn-i Hişâm yapmıştır. Fakat İbn-i Hişâm her satırda İbn-İshâk’ı belirterek olayları anlatmıştır. (İbn-i İshak dedi ki…) Eser, Hz.Muhammed’in hayatına dair günümüze ulaşan en eski ve güvenilir siyer kaynaklarından biridir." },
        { yazar: "İbn Kesîr", eser: "el-Bidâye ve’n-nihâye", aciklama: "Suriye’nin Busra ilçesinde doğmuştur. Dımaşk’ta bulunmuştur. Aldığı eğitimlerden dolayı pek çok medresede öğretim görevlisi olmuştur. Son dönemlerinde gözlerini kaybetmiştir. Eserinde doğruluğundan emin olmadığı şeyleri de aktarır." },
        { yazar: "İbnü’l-Esîr", eser: "el-Kâmil fi’t-Târîḫ", aciklama: "1160’ta Cizre’de doğmuştur. Asıl adı Ali, lakabı İzzeddin’dir. Bağdat, Kudüs, Halep, Dımaşk gibi şehirlerde bulunmuştur. 1188’de Selahaddin Eyyubi ile görüşüp Haçlılara karşı sefere katılmıştır. 1233’te Musul’da vefat etti." },
        { yazar: "Mes’ûdî", eser: "Mürûcü’ẕ-ẕeheb", aciklama: "Bağdat’ta doğmuştur. 912’den sonra çok sayıda İslâm ve gayrimüslim ülkeyi gemiştir: İran, Hindistan, Umman, Arabistan, Irak, Suriye, Hazar, Ermenistan, Mısır, Dımaşk, Antakya vs. Bu eserinde Tarih, coğrafya, din, felsefe, kültür gibi çok geniş bir içeriğe yer vermiştir." },
        { yazar: "Mes’ûdî", eser: "et-Tenbîh ve’l-işrâf", aciklama: "Mes‘ûdî'nin son eseri olduğu düşünülen et-Tenbîh, 955-956 yıllarında yazılmıştır. Kitap, astronomi, meteoroloji, yeryüzündeki yedi bölge ve denizler hakkında bilgiler sunar. Ayrıca, dünya tarihine damgasını vuran toplumlardan (Farslar, Keldânîler, Araplar, Yunanlılar, Romalılar, Kuzey Afrikalılar, Türkler, Hintliler, Çinliler vb.) çeşitli yönleriyle bahsedildikten sonra, İslam tarihi olayları, Hz. Peygamber'den başlayarak dönemin halifesi Mutî‘-Lillâh’a kadar özetlenir. Bu eser, hem bir coğrafya kitabı hem de genel bir tarih kitabıdır." },
        { yazar: "et-Taberî", eser: "Târîḫu’l-ümem ve’l-mülûk", aciklama: "Taberistan’da doğdu. Rey, Bağdat, Küfe, Vasıt, Dımaşk gibi şehirlerde eğitim aldı. Kendi mezhebini oluşturmuş (Cerîriyye/Taberiyye) ve önce Şâfiî iken zamanla müstakil içtihatlarda bulunmuştur. Ahmed b. Hanbel’e eleştirileri, “makām-ı mahmûd” ve kıraatle ilgili bazı aykırı görüşleri Şiîlik ithamına yol açtı. Fakat bu suçlamaları reddederek Ebû Bekir, Ömer ve Osman’ın faziletlerini yazdı. Bağdat’ta vefat ettiğinde Şiîlik ithamları nedeniyle cenazesi gizli kaldırılmış olabilir." },
        { yazar: "İbn Kalânisî", eser: "Târîḫu Dımaşḳ", aciklama: "İbnü'l-Kalânisî, Dımaşk’ta doğmuş ve burada tarih, ilahiyat, edebiyat ve fıkıh eğitimi almıştır. Çeşitli devlet dairelerinde önemli görevlerde bulunmuş, Dımaşk’ta uzun yıllar reislik yapmıştır. Aynı zamanda hadis rivayetleriyle de tanınmıştır. 1160’ta vefat etmiştir. Şair ve hattat olan İbnü'l-Kalânisî, Dımaşk’ta görev yaptığı dönemde şehirdeki önemli olayları kaydeden bir eser yazmıştır. Eseri Târîḫu Dımaşḫ (Dımaşk Tarihi) iki bölümden oluşur. İlk bölüm 1049-1056 yılları arasındaki Dımaşk olaylarına, ikinci bölüm ise 1066-1160 yılları arasındaki gelişmelere odaklanır.  Bu eser, Fâtımîler, Karmatîler, Selçuklular, Zengîler ve Haçlı Seferleri gibi dönemin önemli olaylarına yer verir. Eser, Dımaşk’ın sosyal yapısını, imar faaliyetlerini ve şehirdeki yönetimsel değişiklikleri de ele alır. İbnü'l-Kalânisî, eserini yazarken arşiv belgelerine başvurmuş ve çağdaşı olan bazı tarihçilerden faydalanmıştır. Eser, özellikle Haçlı Seferleriyle ilgili önemli bilgiler sunar ve bu alandaki temel kaynaklardan biridir. " },
        { yazar: "İbnü’l-Adîm", eser: "Buġyetü’ṭ-ṭaleb fî târîḫi Ḥaleb", aciklama: "İbnü’l-Adîm, 1192 yılında Halep’te doğmuş ve burada eğitim almıştır. Halep Eyyûbî hükümdarı tarafından genç yaşta müderrisliğe ve kadılığa atanmış, ardından devlet görevlerinde bulunmuş ve önemli bir devlet adamı olmuştur. Sultan el-Melikü’l-Azîz’in veziri olarak Halep’teki çeşitli sorunların çözülmesinde büyük katkılar sağlamıştır. 1260’ta Moğollar Halep’i fethetmeden önce, Mısır’a gitmiş ve Memlükler'in zaferiyle Halep’e dönmüştür. Ancak şehrin tahrip edilmesi üzerine Kahire’ye yerleşmiş ve orada 1262 yılında vefat etmiştir. İbnü’l-Adîm, Halep'in tarihi ve coğrafyasını ele aldığı Buġyetü’ṭ-ṭaleb fî târîḫi Ḥaleb adlı eseriyle tanınır." }
      ],
      "Bizans Kaynakları": [
        { yazar: "Anna Komnena", eser: "Alexiad", aciklama: "1083’te I.Aleksios’un kızı olarak Bizans sarayında doğdu. Saraydaki “Mor Oda”da doğduğu için “Porfirogenita” (mor odada doğan) unvanına sahiptir. Hem prenses, hem de âlim, doktor, hastane yöneticisi ve tarihçi olarak tanınır. Yedi kardeşin en büyüğüdür ve babasının gözdesi olarak kalmıştır. Kendi anlatımına göre, gençliğinde gizlice antik metinleri okumuş, bu yönüyle kadınlar için sıra dışı bir entelektüeldi. Nikiforos Bryennios ile evlendi. Eşi, hem devlet adamı hem tarihçiydi. Anna, babası tarafından bir hastane ve yetimhane yönetmekle görevlendirilmiş ve burada tıp eğitimi vermiştir. Babasının ölümünden sonra, kardeşi II. İoannis tahta çıkınca, Anna buna karşı çıktı. Eşiyle birlikte tahtı ele geçirmek için komplo kurduğu ileri sürüldü, ancak başarılı olamadı. Bu olaylardan sonra, bir manastıra çekilerek hayatının geri kalanını burada geçirdi. Eserinde, manastıra çekildikten sonra, eşi tarafından başlatılan ama tamamlanamayan tarih eserini bitirdi. Ortaya çıkan eser “Aleksiad”, babası I. Aleksios’un hükümdarlığını (1081–1118) anlatır. Bu eser, Birinci Haçlı Seferi ve dönemin Bizans politikası hakkında çok önemli bilgiler verir." },
        { yazar: "Georges Pachymérés", eser: "Syngrafikai Historiai", aciklama: "1242 yılında İznik'te doğmuş, İstanbul'un Latinler tarafından işgali sonrasında ailesiyle birlikte İstanbul'a göç etmiştir. İlk öğrenimini İznik'te tamamladıktan sonra, 1261'de İstanbul’a gitti ve dönemin ünlü âlimlerinden Georgios Akropolites’in öğrencisi oldu. Kısa zamanda dini ve siyasi makamlar elde ederek, Ayasofya'da çeşitli görevlerde bulundu. Pachymeres, Bizans içindeki olayları yakından takip etti ve özellikle Latin-Ortodoks birliği tartışmalarında muhalefet etti. Türkler, Moğollar, Selçuklular, Osmanlılar ve diğer Türk kavimlerinden de bahseder. Bu eser, Bizans İmparatorluğu'nun iç ve dış olaylarını, özellikle VIII. Mikhail ve II. Andronikos dönemlerini detaylı bir şekilde ele alır. Pachymeres, Türkler ile ilgili birçok önemli olayı kaydetmiş, Osmanlılar’ın adını ilk defa zikretmiştir." }
      ],
      "Ermeni Kaynakları": [
        { yazar: "Aristakes Lastivertsi", eser: "History", aciklama: "XI. yüzyılda yaşamış bir Ermeni tarihçisidir. 1002 civarında doğmuş, 1079'da eserini tamamladıktan kısa süre sonra ölmüştür. Tarihî anlatısı 25 bölümden oluşur; 1047-48’deki Selçuklu saldırılarını, 1064’te Anı şehrinin fethini ve 1071’deki Malazgirt Savaşı’nı ayrıntılı şekilde aktarır." },
        { yazar: "Başkumandan Simbat", eser: "Vekayiname", aciklama: "Simbat, 1208 yılında doğmuş, Kilikya Ermeni Krallığı’nda önemli görevler üstlenmiş bir tarihçi ve devlet adamıdır. Sımbat genç yaşta saraya alınmış ve başkomutan unvanıyla ordu komutanı olmuştur. Selçukluları, Türkmen, Karaman ve Mısır Memlükleri ile yapılan savaşlar, Moğol istilaları ve Ermeni-Moğol ittifakı gibi konular işlenir. Simbat’ın kardeşi Kral I.Hetum, Moğollarla ittifak yapmış; Simbat da bu bağlamda 1248’de elçi olarak Kuyuk Han’a gönderilmiştir. Orada dört yıl kalmış, Kuyuk Han’dan bazı şehirlerin geri verilmesini istemiştir. Kuyuk Han, olumlu karşılık vererek Simbat’ı memnun etmiştir. Simbat, 1275 yılında Mısırlılarla yapılan bir savaşta ölmüştür. Vakayinamesi, 1275 yılına kadar olan olayları kapsar. Bu tarihten sonraki gelişmeler, kimliği belirsiz bir başka yazar (muhtemelen Mareşal Baudouin) tarafından 1331 yılına kadar devam ettirilmiştir. Bu ikinci kısımda esere bazı ilaveler ve düzeltmeler de yapılmıştır. Eserin sonunda, Ermeni Kilisesi’nin yapısı ve patriklik makamlarıyla ilgili bilgiler eklenmiş; bu bölümün Latince kaynaklardan alındığı ve bir Latin yanlısı Ermeni tarafından kaleme alındığı düşünülmektedir." },
        { yazar: "Urfalı Mateos", eser: "Vakayiname", aciklama: "Mateos yaklaşık 1070 yıllarında Urfa’da doğmuş Ermeni bir tarihçidir. Bu eserinde, 952 yılından 1128/1129’a kadar yaşanan önemli olayları ay ve yıl vererek kaydetmiştir. Mateos’un ölümünden sonra, kroniğin devamını Gregor adlı bir rahip getirerek 1162/1163 yılına kadar uzatmıştır. Eser, 12. yüzyılın ilk yarısında yazılmıştır ve dönemin tarihine ışık tutan önemli kaynaklardan biridir." }
      ],
      "Haçlı Kaynakları": [
        { yazar: "Anonim Haçlı Savaşçısı", eser: "Gesta Francorum et Aliorum Hierosolymitanorum (Frankların ve Diğer Kudüs Yolcularının İşleri) ", aciklama: "Eser, 1095 yılında Papa II. Urbanus’un Clermont Konseyi’nde yaptığı çağrıdan başlayarak, 1099’da Kudüs’ün fethine ve hemen sonrasındaki Askalan Savaşı’na kadar geçen süreci anlatır. Toplam 39 fasıldan oluşur. Eser, yazarın bizzat katıldığı veya duyduğu olayları ay ay, yıl yıl, kronolojik biçimde aktarır. Bu yönüyle hem günlük, hem vakayiname, hem de propagandatif tarih niteliği taşır. Birinci elden kaynak niteliğindedir; yazar olaylara şahit olmuş, çoğunu yaşamıştır. Üslubu sade, doğrudan, duygusal ve samimidir. Özellikle Türklerle yapılan savaşlardaki korkularını açıkça dile getirmesi dikkat çekicidir.  Yazar, Hristiyanlığı merkeze alan bir bakış açısına sahiptir. Müslümanlar ve Türkler için “kâfir”, “imansız” gibi ifadeler kullanır. Ancak buna rağmen Türklerin cesaretini ve askerî yeteneğini takdir eder. Eser, zaman zaman duyuma ve söylentiye dayalı bilgiler de içerir (örneğin diplomatik görüşmeler), fakat çoğu kayıt diğer kaynaklarla da örtüşür. Haçlı Seferlerini “savunma savaşı” olarak meşrulaştırır. İslam dünyasını medeni ve dinî bir tehdit olarak görür. Bizans’a karşı mesafeli, hatta zaman zaman eleştireldir. " },
        { yazar: "Raimundus Aguilers", eser: "Historia Francorum Qui Ceperunt Iherusalem ", aciklama: "Bu eser, I. Haçlı Seferi’nin katılımcılarından Raymond de Toulouse'un (Raymond St. Gilles) yani Güney Fransızların bakış açısından olayları başlangıçtan Kudüs'e kadar seferin gidişatının aktarmasının yanında Haçlılar arasındaki hizipleşme, Kutsal Mızrak hikayesi, Kudüs'ü ele geçirmelerinin sonrasında Haçlılar arasında yaşanan liderlik çekişmelerini anlatmaktadır." }
      ],
      "Selçuklu Kaynakları": [
        { yazar: "İbn Bîbî", eser: "el-Evâmirü’l-ʿAlâʾiyye", aciklama: "İranlıdır.  Annesi Bîbî Müneccime, dönemin nadir kadın âlimlerinden biridir; müneccimlikte (astroloji) yetkindir ve Selçuklu sultanlarının yanında bulunmuştur. Babası Mecdüddin Muhammed, Cürcânlıdır ve tercümanlık, münşîlik gibi bürokratik görevlerde bulunmuştur. Aile, 1231-1233 yıllarında Anadolu’ya gelip I. Alâeddin Keykubad’ın hizmetine girmiştir. İbn Bîbî, babasının ölümünden sonra devlet hizmetine alınmış; özellikle tuğra ve inşa divanı reisliği gibi önemli görevler üstlenmiştir. III. Gıyâseddin Keyhusrev ve İlhanlı idaresi döneminde aktif görevde bulunmuştur. İlhanlı tarihçisi Alâeddin Atâ Melik Cüveynî’nin isteğiyle, Selçuklu tarihini kaleme almıştır.  Eser, “Alâeddin’in İşleri Üzerine Emirler”; hem Alâeddin Keykubad hem de Atâ Melik Cüveynî’ye ithafen bu isim verilmiştir. Yazılış amacı, Anadolu Selçukluları tarihini, özellikle Alâeddin Keykubad ve sonrası dönemleri anlatmak. Türkmenler ve halk grupları hakkında zaman zaman olumsuz ifadeler kullanır. Saray hayatı, düğünler ve eğlencelere yer verir ama halkın sosyal durumu çok ele alınmaz. Şiirsel ve ağır üslup, eseri anlaşılması zor kılar. Tam bir İranlıdır. Ancak Selçuklu hanedanına aşırı bağlılığı, bazı olayları örtmesine veya çarpıtmasına neden olmuştur. Mevlânâ, Hacı Bektaş gibi önemli figürlerden hiç bahsetmemesi dikkat çekicidir." },
        { yazar: "Anonim Selçuknâme", eser: "Tarîh-î Âl-i Selçuk", aciklama: "Eserin dili Farsçadır. Müellif, tarihî olayları günü gününe aktarmaya çalışsa da eserde özellikle erken bölümlerde çok sayıda yanlış ve efsanevi bilgiye yer verilmiştir. Bununla birlikte, İbn Bîbî ve Aksarâyî gibi kaynakların eksik bıraktığı yerlerde verdiği kısa ama özgün bilgilerle dikkat çekmektedir. Eserin, XIII. yüzyılın sonlarında yazıldığı ve XIV. yüzyıl ortalarında başka biri tarafından kısa bir takvimle tamamlandığı düşünülmektedir. Eserde Moğol istilası, İlhanlılar, Karamanoğulları gibi siyasi aktörlere dair önemli bilgiler yer almakta, ayrıca Cengiz Han, Hârezmşâhlar ve Abbâsîler hakkında da bilgiler sunulmaktadır." },
        { yazar: "Reşîdü’d-dîn Fazlulah", eser: "Cami’ü’t-tevârih", aciklama: "İlhanlılar döneminde yaşamış seçkin bir devlet adamı, âlim ve tabiptir. Onun eseri modern anlamda kaleme alınmış ilk dünya tarihi olarak kabul edilir. Eser, İlhanlı hükümdarı Gazan Han’ın isteğiyle yazılmış ve İslam döneminde Türk tarihinin temel kaynaklarından biri olarak değerlendirilmiştir. Reşidü’d-din, bu çalışmasında farklı millet ve kültürleri tarafsız bir bakış açısıyla ele almış, Asya ve Avrupa’daki kavim ve devletlerin tarihini geniş bir çerçevede sunmuştur. Gazan Han’ın eserin tamamlanmasından önce vefat etmesi üzerine Reşidü’d-din, eseri onun halefi Olcaytu’ya ithaf etmek istemiş; ancak Olcaytu bu teklifi reddederek kendisi için ayrı bir tarih yazılmasını istemiştir. Bu nedenle birinci cilt, Târîḫ-i Gazânî / Dâstân-ı Gazan Han gibi adlarla anılmıştır." },
        { yazar: "Ahmet Eflâkî", eser: "Âriflerin Menkıbeleri", aciklama: "Ahmed Eflâkî, asıl adıyla tanınsa da genellikle Eflâkî olarak bilinir. Mevlânâ'nın oğlu Ulu Ârif Çelebi'ye bağlanması nedeniyle 'Ârifî'' nisbesiyle de anılır. Doğum tarihi ve yeri kesin olarak bilinmemekle birlikte, 1286-1291 yılları arasında doğmuş olabileceği tahmin edilir. Ailesi hakkında çok bilgi yoktur, ancak babasının ölümünde ona büyük bir servet ve kitaplar bıraktığı için kültürlü bir aileden geldiği söylenebilir. Eflâkî, Konya'da eğitim almış ve burada önemli alimlerden dersler almıştır. Aynı zamanda astronomiyle ilgilenmiş, bu yüzden 'Eflâkî'' adını almıştır. Mevlânâ'nın oğlu Ulu Ârif Çelebi'ye intisap etmiş ve onun seyahatlerine katılmıştır. Ulu Ârif Çelebi'nin ölümünden sonra, Eflâkî farklı Mevlevi şeyhlerine intisap etmiş ve eserlerini genişletmiştir. En tanınan eseri 'Menâḫıbü’l-ʿârifîn'dir ve bu eser, Mevlevi tarikatının öğretileri ile mürşitlerin hayat hikayelerini içerir. Eflâkî 1360 yılında vefat etmiştir. Ayrıca dört Türkçe gazeli de bulunmaktadır." }
      ],
      "Seyahatnâmeler": [
        { yazar: "İbn Battûta", eser: "Seyahatnâme (Rıhle)", aciklama: "Fas'ın Tanca şehrinde doğmuş önemli bir 14. yüzyıl gezginidir. Yaklaşık 28 yıl süren seyahatleri boyunca Mısır, Arap Yarımadası, İran, Irak, Anadolu (özellikle Osmanlı ve diğer beylikler), Deşt-i Kıpçak, Bizans (İstanbul), Orta Asya, Hindistan, Maldivler, Çin ve Endülüs gibi birçok bölgeyi gezmiştir. Seyahatleri sırasında gördüğü toplumların devlet yapıları, inanç sistemleri, gelenekleri ve doğal kaynakları hakkında ayrıntılı bilgiler sunarak, bu coğrafyaların 14. yüzyıldaki durumunu başarılı biçimde yansıtmıştır. İbn Battûta, seyahat notlarını 'Tuhfetü’n-Nuzzâr fî Garâibi’l-Emsâr ve Acâibi’l-Esfâr' adıyla derlemiş; bu eser yaygın olarak 'Rıhle' (Seyahat) adıyla tanınır. Türkçeye 'İbn Battûta Seyahatnamesi' adıyla çevrilmiştir." },
        { yazar: "Marco Polo", eser: "Seyahatnâme", aciklama: "Marco Polo, 1254 yılında Venedik'te doğmuş, ünlü bir gezgin ve tüccardır. Babası Niccolo Polo ve amcası Matteo ile Asya'ya 24 yıl süren bir seyahate çıkmış ve Kubilay Han ile tanışmıştır. Bu süre boyunca Uzak Doğu ile ticaret yolları geliştirmiş ve 'risk sermayesi'nin ilk örneklerini oluşturmuştur. Döndüklerinde Venedik'te Cenevizliler tarafından esir alınmış, hikâyelerini hücre arkadaşına yazdırmıştır. 1299'da serbest kaldıktan sonra zengin bir tüccar olmuş, evlenip çocukları olmuştur. 1324'te ölmüş ve son sözleri 'Kimse bana inanmayacağı için gördüklerimin yarısını bile anlatmadım' olmuştur. Polo'nun Çin'e dair detaylı kitabı, Kristof Kolomb ve diğer gezginlere ilham vermiştir." }
      ],
      "Coğrafi Kaynaklar": [
        { yazar: "İbn Havkal", eser: "Sûretü’l-arż", aciklama: "İbn Havkal, 937 yılında Bağdat’ta doğmuş ve Nusaybinli bir ailenin çocuğudur. Gençliğinde ticaretle uğraşmış, farklı yerlerde okuduğu eserleri ve duyduğu bilgileri kendi gözlemleriyle pekiştirmek amacıyla seyahatler yapmıştır. 943-977 yılları arasında İslam dünyasında geniş bir seyahat yaparak, bu gezileri sırasında topladığı notları Ṣûretü’l-arż adlı eserinde toplamıştır. Eser, Arap Yarımadası, Kuzey Afrika, Endülüs, Sicilya, Mısır, Suriye, İran, Horasan, Batı Türkistan gibi bölgeleri kapsayan coğrafi bilgileri içerir. İbn Havkal, gezdiği yerlerdeki siyasi, idari, ekonomik durumu, halkları ve ticaret hayatını detaylı şekilde aktarmıştır. Ṣûretü’l-arż, diğer coğrafyacılardan farklı olarak, bir bölgedeki geçmiş durumu ve değişiklikleri de ele alır. Ayrıca ticaret, tarım ve diğer ekonomik faaliyetlerle ilgili sağlam bilgilere sahiptir." }
      ]
    };

const menu = document.getElementById("menu");
const content = document.getElementById("content");
const hamburger = document.getElementById("hamburger");

for (const kategori in kaynaklar) {
  const menuItem = document.createElement("h2");
  menuItem.textContent = kategori;
  menuItem.onclick = () => renderKategori(kategori);
  menu.appendChild(menuItem);
}

function renderKategori(kategori) {
  content.innerHTML = `<h2 style="color:#2d6a4f;">${kategori}</h2>`;
  kaynaklar[kategori].forEach(entry => {
    const authorDiv = document.createElement("div");
    authorDiv.classList.add("author");

    const button = document.createElement("button");
    button.textContent = entry.yazar;

    const contentBox = document.createElement("div");
    contentBox.classList.add("author-content");
    contentBox.innerHTML = `<strong>Eser:</strong> ${entry.eser}<br><br>${entry.aciklama}`;

    button.onclick = () => {
      contentBox.style.display = contentBox.style.display === "block" ? "none" : "block";
    };

    authorDiv.appendChild(button);
    authorDiv.appendChild(contentBox);
    content.appendChild(authorDiv);
  });
}

const ilkKategori = Object.keys(kaynaklar)[0];
renderKategori(ilkKategori);

// Hamburger menü kontrolü
hamburger.addEventListener("click", () => {
  document.querySelector(".sidebar").classList.toggle("open");
});
